version: "3"
services:
  mongo:
    container_name: local_mongo
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"

  mysql:
    container_name: local_mysql
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=var_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=userpass
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"

  app:
    container_name: graphqlapp
    restart: always
    build: ./graphql_service
    ports:
      - "4000:4000"
    links:
      - mongo
      - mysql
    depends_on:
      - mongo
      - mysql

  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    depends_on:
      - mongo
    links:
      - mongo

  fhir:
    container_name: gofhir
    build: ./gofhir
    command: -db.host mongo
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo
